export const withdrawal: string;
export const form: string;
export const title: string;
export const form-item: string;
export const label: string;
export const unit: string;
export const desc: string;
export const btn: string;
export const notice: string;